### ISSUE TITLE
How to install for Bitbucket

### ISSUE THREAD

**Issue by fabianderijk** [Lullabot/drupal9ci#89]
As described in https://github.com/Lullabot/drupal9ci?tab=readme-ov-file#bitbucket I try to run the `./drupal9ci` script but I get a error: `bash: ./drupal9ci: cannot execute binary file`

The docs say, just download the binary and execute, however it seems like that there is some more work in it. Just to be clear, the file has been execution permissions with `chmod +x drupal9ci`

Can anybody help me with this?

**Comment by juampynr** [comment]
Hi @fabianderijk, I am also seeing this. Are you on a Mac? I am on a Mac M now and I am also seeing this error. I think that it is caused by the fact that the project builds with default params, which does not produce an executable compatible with my laptop's architecture.

The issue is at https://github.com/Lullabot/drupal9ci/blob/master/.github/workflows/create-release.yml#L18. I am going to take a look at how to tweak that GitHub action so it builds multiple artifacts for different architectures. Feel free to help if you know about this.

**Comment by fabianderijk** [comment]
Hi @juampynr I have a macbook M1 as well, so that could be the issue. Unfortunately I am not able to help out just because of lack of knowledge

**Comment by juampynr** [comment]
No worries @fabianderijk ! I will find time this week to fix it.
